Token and CRUD operations of user and projects
leapfrogtechnology/chill-rest-api pull request #5
Opened 2017-08-28 05:22 UTC by lhamu

2017-08-31 04:12 UTC, badyakarprabin commented on src/config/passport.js
> +    let data = {
Can we do this here?  
```
const { id,  displayName, emails,  _json} = profile ;

let data = {
  'id': id,
  'name': displayName,
  'email': emails[0].values,
  'accessToken': accessToken,
  'image': _json.image.url
}
```

2017-08-31 04:28 UTC, badyakarprabin commented
Things to remember before creating PR:

- Remove unwanted codes ( commented code).
- Write proper JS Docs.

Useful Tips:
[Auto code formatting while saving
](https://stackoverflow.com/questions/12496669/code-reformatting-on-save-in-phpstorm)
[ Contributing guidelines](https://github.com/leapfrogtechnology/chill/blob/master/CONTRIBUTING.md)

2017-09-01 02:44 UTC, deepsadhi requested changes
1. Import npm packages at top and custom packages separated by blank line
2. Indent code properly with spacing  
3. Use of doc block 
4. Remove use of return keyword if return statement is of single line [  func1(obj => func2(obj2))  ] 
5. Remove console.log before code is pushed
6. Remove ' from object key. Eg. { name: 'ABC' } instead of { 'name': 'ABC' }
7. If key and variable is same of object use { name } instead of { name: name }
8. Order statements by statement length order
9. Follow same if syntax indentation by everyone
10. Remove comments if not required
11. Do not leave multiple lines, one line is enough
12. Write all SQL keywords in UPPERCASE
13. Remove magic numbers. Use constant instead of it
14. Use of single quote ' instead of double quote "

2017-09-01 02:44 UTC, deepsadhi commented on src/app.js
> +import passport from 'passport';
Can we move these lines to top?

2017-09-01 02:44 UTC, deepsadhi commented on src/config/passport.js
> +import * as clientInfo from './auth';
Reorder statement with by statement length

2017-09-01 02:44 UTC, deepsadhi commented on src/app.js
> +
Remove line

2017-09-01 02:44 UTC, deepsadhi commented on src/config/passport.js
> +// import * as User from '../models/users';
If this comment is not required lets remove it

2017-09-01 02:44 UTC, deepsadhi commented on src/config/passport.js
> +/*
Indent comments properly

2017-09-01 02:44 UTC, deepsadhi commented on src/config/passport.js
> +    let data = {
```js
let data = {
  id,
  accessToken,
  name: displayName,
  image: _json.image.url,
  email: emails[0].values
}
```

2017-09-01 02:44 UTC, deepsadhi commented on src/config/passport.js
> +  passport.serializeUser(function(user, done) {
```js
passport.serializeUser((user, done) => done(null, user));
```

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/profile.js
> +// import * as authenticate from '../middlewares/authenticate';
Let's remove comment if not required

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/profile.js
> +// router.post('/', (request, response)=>{
Let's remove comment if not required

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/profile.js
> +router.get('/', (request, response)=>{
* Proper spacing and indentation
* Use return in same line if there is only one statement
```js
router.get('/', (request, response) => response.json('User profile'));
```

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +import jwt from 'jsonwebtoken';
Import npm packages at top and then import custom code separated by a blank line
```js
import jwt from 'jsonwebtoken';

import * as projectService from '../services/project';
import * as userProjectService from '../services/userProject';
```

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +/*
Indent properly

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +export function create( req, res, next ) {
```js
export function create(req, res, next) {
```

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +  projectService.create( req.body )
Same here

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +            // Call userproject service to map user and project
Indent properly

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +      // res.json(userProjectData);
Remove line if not required

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +        .then(userprojectreturn =>{
Proper spacing

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +  projectService.deleteProject(value.userId, req.params.projectid )
```js
projectService.deleteProject(value.userId, req.params.projectid)
```

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/project.js
> +  projectService.updateProject( value.userId, req.params.projectid , req.body )
```js
projectService.updateProject(value.userId, req.params.projectid, req.body)
```

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/users.js
> +create a user
Indentation

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/users.js
> +fetch a user from id
Same here

2017-09-01 02:44 UTC, deepsadhi commented on src/controllers/users.js
> +    // console.log('hello');
Let 's remove console.log

2017-09-01 02:44 UTC, deepsadhi commented on src/middlewares/checkToken.js
> +import * as tokenServices from '../services/token';
Import order

2017-09-01 02:44 UTC, deepsadhi commented on src/queries/project.js
> +    select *
* Use of SQL keywords in UPPERCASE
* Do we require bracket `()`?
```js
export const FETCH_All_PROJECTS = `
  SELECT * 
  FROM users u  
  LEFT JOIN user_project up ON up.user_id = u.id 
  LEFT JOIN projects p ON up.project_id = p.id 
  WHERE u.id = ?;
`
```

2017-09-01 02:44 UTC, deepsadhi commented on src/services/user.js
> +      let accessToken = generateTokens.generateToken(userInfo.id, 'RESTFULAPI', 300);
Remove magic numbers. Use constants instead.

2017-09-01 05:23 UTC, romitamgai commented
This is old pull request. Closing this. Thanks for the comments though @deepsadhi

2017-09-01 05:23 UTC, closed without merging