Chill CRUD
leapfrogtechnology/chill-rest-api pull request #6
Opened 2017-08-29 08:14 UTC by lhamu

2017-08-30 08:27 UTC, romitamgai requested changes

2017-08-30 08:27 UTC, romitamgai commented on src/middlewares/checkToken.js
> +const REFRESHTOKEN_AUTHENTICATION_SALT_KEY = 'CHILL_REFRESH';
lets keep these in env file

2017-08-30 08:27 UTC, romitamgai commented on src/middlewares/checkToken.js
>  export async function authenticateRefreshToken(req, res, next) {
refactor this like that of authentication middleware

2017-08-30 08:27 UTC, romitamgai commented on src/models/Service.js
> +      logger().error('Error while persisting the service into database', err);
don't we need to throw error here?

2017-08-30 08:27 UTC, romitamgai commented on src/models/Service.js
> +      logger().error('Error while persisting the service into database', err);
do we need to throw err from here?

2017-08-30 08:27 UTC, romitamgai commented on src/services/token.js
> +const REFRESH_TOKEN_SALT_KEY = 'CHILL_REFRESH';
keep these in env file

2017-08-30 08:27 UTC, romitamgai commented on src/services/tokenGeneration.js
> +const REFRESH_TOKEN_SALT_KEY = 'CHILL_REFRESH';
keep these in env file

2017-08-30 08:27 UTC, romitamgai commented on src/services/user.js
> +const REFRESH_TOKEN_SALT_KEY = 'CHILL_REFRESH';
keep these in env file

2017-08-30 08:44 UTC, kabirbaidhya commented on src/queries/userProject.js
> +export const CHECK_USER_PROJECT = (`
```js
export const CHECK_USER_PROJECT = `
  SELECT first_name, last_name
  FROM table_name
  INNER JOIN test ON t.id = s.user_id
  WHERE
  GROUP BY
`;

2017-08-30 08:53 UTC, kabirbaidhya commented on src/services/service.js
> +export async function fetchAll( id ,  userId ) {
```
export async function fetchAll(id, userId) {
```

2017-08-30 08:53 UTC, kabirbaidhya commented on src/services/service.js
> +export async function fetchAll( id ,  userId ) {
```
let a = { name: 'test' };

import { name } from 'test';
```

2017-08-30 09:35 UTC, mesaugat commented on src/services/service.js
> +export async function fetchAll( id ,  userId ) {
We need prettier.

2017-08-30 09:45 UTC, kabirbaidhya commented
Install `prettier` extenstion in `vscode`. Enable it on save after that setting `"editor.formatOnSave": true`. @lhamu @andreshsingh @leapfrogtechnology/the-chill-team

2017-08-30 14:42 UTC, kabirbaidhya commented on src/queries/service.js
>  export const FETCH_All_SERVICE = (`
let's remove the additional bracket `(` or `)` from all the raw queries.

2017-08-30 14:44 UTC, kabirbaidhya requested changes

2017-08-30 14:44 UTC, kabirbaidhya commented on src/queries/project.js
> +    DELETE
Use raw queries ONLY for complex `SELECT` queries that affects readability if done with query builder. Not for `UPDATE`, `DELETE`, `INSERT` and trivial queries like `SELECT * FROM table`.

2017-08-30 15:45 UTC, pratishshr commented on src/middlewares/checkToken.js
> +const REFRESHTOKEN_AUTHENTICATION_SALT_KEY = 'CHILL_REFRESH';
Get the salt from chill.yml
Salts should not be in the code itself.

2017-08-31 03:55 UTC, kabirbaidhya requested changes

2017-08-31 03:55 UTC, kabirbaidhya commented on src/config/auth.js
> +  googleAuth: {
We store all our configuration in the `chill.yml` file. No need additional config files.

2017-08-31 03:55 UTC, kabirbaidhya commented on .gitignore
> +src/config/auth.js
No need to ignore additional config files. As we already have `chill.yml`

2017-08-31 03:55 UTC, kabirbaidhya commented on src/app.js
>  passportConfig(passport);
```js
passportConfig(config.get().passport);
```

2017-08-31 03:55 UTC, kabirbaidhya commented on src/app.js
>  import passportConfig from './config/passport';
No need to import additional config files

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/project.js
> +  WHERE u.id = ? ;
named parameter

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/project.js
> +  WHERE u.id = ? ;
named parameter

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/project.js
> +export const DELETE_A_PROJECT_USERPROJECT = `
here

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/project.js
> +export const UPDATE_A_PROJECT_PROJECTS = `
here

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/service.js
> +  SELECT *
no need raw query for this

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/service.js
> +export const FETCH_A_SERVICE = `
and this

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/service.js
> +export const DELETE_A_SERVICE = `
this as well

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/service.js
> +export const UPDATE_A_SERVICE_SERVICES = `
this

2017-08-31 03:55 UTC, kabirbaidhya commented on src/queries/userProject.js
> +	SELECT *
indentation

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/service.js
> + * @param  {string|Number}  projectId, serviceId
incorrect doc block

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/service.js
> + * @param {Object}
incorrect

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/token.js
> +import * as key from '../config/key';
here

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/token.js
> +    jwt.verify(refreshToken, key.REFRESH_TOKEN_SALT_KEY);
```js
jwt.verify(refreshToken, config.get().auth.saltKey);
```

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/token.js
> +        key.AUTHORIZATION_SALT_KEY,
```js
jwt.verify(refreshToken, config.get().auth.saltKey);
```

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/tokenGeneration.js
> +      key.REFRESH_TOKEN_SALT_KEY,
```
jwt.verify(refreshToken, config.get().auth.saltKey);
```

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/user.js
> +        key.AUTHORIZATION_SALT_KEY,
```js
config.get().auth.saltKey
```

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/user.js
> +        key.AUTHORIZATION_SALT_KEY,
here

2017-08-31 03:55 UTC, kabirbaidhya commented on src/services/user.js
> +        key.REFRESH_TOKEN_SALT_KEY,
here

2017-09-01 05:29 UTC, kabirbaidhya commented
Reminder: As previously added by @deepsadhi in the other PR

1. Import npm packages at top and custom packages separated by blank line
2. Indent code properly with spacing  
3. Use of doc block 
4. Remove use of return keyword if return statement is of single line `[  func1(obj => func2(obj2))  ]` 
5. Remove console.log before code is pushed
6. Remove ' from object key. Eg. `{ name: 'ABC' }` instead of `{ 'name': 'ABC' }`
7. If key and variable is same of object use `{ name }` instead of `{ name: name }`
8. Order statements by statement length order
9. Follow same if syntax indentation by everyone
10. Remove comments if not required
11. Do not leave multiple lines, one line is enough
12. Write all SQL keywords in UPPERCASE
13. Remove magic numbers. Use constant instead of it
14. Use of single quote ' instead of double quote "

@lhamu @andreshsingh

2017-09-01 11:52 UTC, romitamgai approved these changes

2017-09-01 11:53 UTC, merged